name: 'kommineni_automotive'
version: '1.0.0'
config-version: 2

profile: 'kommineni_automotive'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  kommineni_automotive:
    staging:
      +schema: silver
      +materialized: table
    marts:
      +schema: gold
      +materialized: table